
---five9_agente>>>
--Se crea Tabla Temporal con las trasformaciones aplicadas a la tabla bronze (Agente):
with tmpstaging_five9_agente as(
  SELECT DISTINCT
        TRIM(AGENT_ID) ID_AGENTE,
        TRIM(AGENT) AGENTE,
        INITCAP(TRIM(AGENT_FIRST_NAME)) PRIMER_NOMBRE_AGENTE, 
        INITCAP(TRIM(AGENT_LAST_NAME)) APELLIDO_AGENTE, 
        INITCAP(TRIM(AGENT_NAME)) NOMBRE_AGENTE,
        TRIM(AGENT_EMAIL) CORREO_ELECTRONICO_AGENTE,
        TRIM(EXTENSION) EXTENSION,
        to_date(AGENT_START_DATE,'yyyy/MM/dd') FECHA_INICIO_AGENTE,
        INITCAP(TRIM(AGENT_START_MONTH)) MES_INICIO_AGENTE,
        TRIM(AGENT_START_YEAR) ANO_INICIO_AGENTE,
        TRIM(AGENT_GROUP) GRUPO_AGENTES,
        TRIM(ENABLED_FOR_VIDEO) HABILITADO_VIDEO,
        TRIM(STATE) ESTADO,
        TRIM(AGENT_STATES) ESTADOS_AGENTES,
        TRIM(REASON_CODE) CODIGO_RAZON,
        date_format(LOGIN_TIME,'HH:mm:ss') HORA_CONEXION,
        date_format(to_timestamp(trim(substring(LOGIN_TIMESTAMP,7,20)),'d MMM yyyy HH:mm:ss'),'yyyy-MM-dd HH:mm:ss') MARCA_HORA_CONEXION,
        date_format(LOGOUT_TIME,'HH:mm:ss') HORA_DESCONEXION,
        date_format(to_timestamp(trim(substring(LOGOUT_TIMESTAMP,7,20)),'d MMM yyyy HH:mm:ss'),'yyyy-MM-dd HH:mm:ss') MARCA_HORA_DESCONEXION,
        date_format(VIDEO_TIME,'HH:mm:ss') DURACION_VIDEO,
        TRIM(AVAILABLE_FOR_CALLS) DISPONIBLE_LLAMADAS,
        TRIM(MEDIA_AVAILABILITY) DISPONIBILIDAD_MEDIOS,
        TRIM(SKILL_AVAILABILITY) DISPONIBILIDAD_COMPETENCIAS,
        TRIM(AVAILABLE_FOR_VM) DISPONIBLE_CORREO_VOZ,
        TRIM(AVAILABLE_FOR_ALL) DISPONIBLE_TODAS,
        date_format(AGENT_STATE_TIME,'HH:mm:ss') TIEMPO_ESTADO_AGENTE,
        date_format(WAIT_TIME,'HH:mm:ss') TIEMPO_ESPERA,
        date_format(RINGING_TIME,'HH:mm:ss') TIEMPO_TIMBRE,
        date_format(MANUAL_TIME,'HH:mm:ss') TIEMPO_MANUAL,
        date_format(ON_CALL_TIME,'HH:mm:ss') TIEMPO_UNA_LLAMADA,
        date_format(PAID_TIME,'HH:mm:ss') TIEMPO_PAGADO,
        date_format(UNPAID_TIME,'HH:mm:ss') TIEMPO_NO_PAGADO,
        date_format(ON_ACW_TIME,'HH:mm:ss') TIEMPO_ACW,
        date_format(READY_TIME,'HH:mm:ss') TIEMPO_LISTO,
        date_format(NOT_READY_TIME,'HH:mm:ss') TIEMPO_NO_LISTO,
        date_format(ON_VOICEMAIL_TIME,'HH:mm:ss') TIEMPO_CORREO_VOZ,
        date_format(VM_IN_PROGRESS_TIME,'HH:mm:ss') TIEMPO_CORREO_VOZ_CURSO,
        TRIM(UNAVAILABLE_FOR_CALLS) NO_DISPONIBLE_LLAMADAS,
        TRIM(UNAVAILABLE_FOR_VM) NO_DISPONIBLE_CORREO_VOZ,
        date_format(TIMESTAMP_MILLISECOND, 'yyyy-MM-dd HH:mm:ss.SSS') FECHAHORA,
        TRIM(DATE) FECHA,
        TRIM(TIME) HORA,
        CAST(TIMESTAMP_ID AS BIGINT) AS TIMESTAMP_ID
  ---FROM bronze.five9_agente
  FROM raw.five9_agente
  WHERE CAST(TRIM(DATE) AS date) > date_add(current_date(), -7)
);


--Se eliminan de Tabla Silver los registros que existan en la tabla bronze (Campopivot(TIMESTAMP_ID)) para luego ser insertadas:
--DELETE FROM silver.cet_seguimientoagente
DELETE FROM master.cet_seguimientoagente
WHERE TIMESTAMP_ID IN ( SELECT DISTINCT TIMESTAMP_ID
                        FROM tmpstaging_five9_agente
                      );


--Se insertan los nuevos registros por (Campopivot(TIMESTAMP_ID)).  staging.tmp_five9_agente
--INSERT INTO silver.cet_seguimientoagente (
INSERT INTO master.cet_seguimientoagente (
    ID_AGENTE,
    AGENTE,
    PRIMER_NOMBRE_AGENTE,
    APELLIDO_AGENTE,
    NOMBRE_AGENTE,
    CORREO_ELECTRONICO_AGENTE,
    EXTENSION,
    FECHA_INICIO_AGENTE,
    MES_INICIO_AGENTE,
    ANO_INICIO_AGENTE,
    GRUPO_AGENTES,
    HABILITADO_VIDEO,
    ESTADO,
    ESTADOS_AGENTES,
    CODIGO_RAZON,
    HORA_CONEXION,
    MARCA_HORA_CONEXION,
    HORA_DESCONEXION,
    MARCA_HORA_DESCONEXION,
    DURACION_VIDEO,
    DISPONIBLE_LLAMADAS,
    DISPONIBILIDAD_MEDIOS,
    DISPONIBILIDAD_COMPETENCIAS,
    DISPONIBLE_CORREO_VOZ,
    DISPONIBLE_TODAS,
    TIEMPO_ESTADO_AGENTE,
    TIEMPO_ESPERA,
    TIEMPO_TIMBRE,
    TIEMPO_MANUAL,
    TIEMPO_UNA_LLAMADA,
    TIEMPO_PAGADO,
    TIEMPO_NO_PAGADO,
    TIEMPO_ACW,
    TIEMPO_LISTO,
    TIEMPO_NO_LISTO,
    TIEMPO_CORREO_VOZ,
    TIEMPO_CORREO_VOZ_CURSO,
    NO_DISPONIBLE_LLAMADAS,
    NO_DISPONIBLE_CORREO_VOZ,
    FECHAHORA,
    FECHA,
    HORA,
    TIMESTAMP_ID
)  
  SELECT DISTINCT
          ba.ID_AGENTE,
          ba.AGENTE,
          ba.PRIMER_NOMBRE_AGENTE,
          ba.APELLIDO_AGENTE,
          ba.NOMBRE_AGENTE,
          ba.CORREO_ELECTRONICO_AGENTE,
          ba.EXTENSION,
          ba.FECHA_INICIO_AGENTE,
          ba.MES_INICIO_AGENTE,
          ba.ANO_INICIO_AGENTE,
          ba.GRUPO_AGENTES,
          ba.HABILITADO_VIDEO,
          ba.ESTADO,
          ba.ESTADOS_AGENTES,
          ba.CODIGO_RAZON,
          ba.HORA_CONEXION,
          ba.MARCA_HORA_CONEXION,
          ba.HORA_DESCONEXION,
          ba.MARCA_HORA_DESCONEXION,
          ba.DURACION_VIDEO,
          ba.DISPONIBLE_LLAMADAS,
          ba.DISPONIBILIDAD_MEDIOS,
          ba.DISPONIBILIDAD_COMPETENCIAS,
          ba.DISPONIBLE_CORREO_VOZ,
          ba.DISPONIBLE_TODAS,
          ba.TIEMPO_ESTADO_AGENTE,
          ba.TIEMPO_ESPERA,
          ba.TIEMPO_TIMBRE,
          ba.TIEMPO_MANUAL,
          ba.TIEMPO_UNA_LLAMADA,
          ba.TIEMPO_PAGADO,
          ba.TIEMPO_NO_PAGADO,
          ba.TIEMPO_ACW,
          ba.TIEMPO_LISTO,
          ba.TIEMPO_NO_LISTO,
          ba.TIEMPO_CORREO_VOZ,
          ba.TIEMPO_CORREO_VOZ_CURSO,
          ba.NO_DISPONIBLE_LLAMADAS,
          ba.NO_DISPONIBLE_CORREO_VOZ,
          ba.FECHAHORA,
          ba.FECHA,
          ba.HORA,
          ba.TIMESTAMP_ID
  --FROM staging.tmp_five9_agente AS ba
  FROM tmpstaging_five9_agente AS ba
  --LEFT JOIN silver.cet_seguimientoagente AS sa
  LEFT JOIN master.cet_seguimientoagente AS sa
    ON ba.TIMESTAMP_ID = sa.TIMESTAMP_ID
  WHERE sa.TIMESTAMP_ID IS NULL;


---five9_contacto>>>
--Se crea Tabla Temporal con las trasformaciones aplicadas a la tabla bronze (Contacto):
with tmpstaging_five9_contacto AS(
--CREATE OR REPLACE TABLE tmpstaging_five9_contacto AS
  SELECT DISTINCT
        TRIM(CONTACT_ID) ID_CONTACTO,
        TRIM(ID) ID,
        TRIM(IDSOLICITUD) ID_SOLICITUD,
         CASE
            WHEN length(TRIM(FECHALLEGADALEAD)) = 10 AND TRY_CAST(TRIM(FECHALLEGADALEAD) AS date) IS NOT NULL 
                  THEN TRY_CAST(TRIM(FECHALLEGADALEAD) AS date)
            WHEN length(TRIM(FECHALLEGADALEAD)) < 11 AND TRY_CAST(TRIM(FECHALLEGADALEAD) AS date) IS NOT NULL 
                  THEN to_date(TRIM(FECHALLEGADALEAD),'d/MM/yyyy')
            WHEN length(TRIM(FECHALLEGADALEAD)) = 20 AND TRY_CAST(TRIM(substring(TRIM(FECHALLEGADALEAD),0,9)) AS date) IS NOT NULL 
                  THEN to_date(substring(TRIM(FECHALLEGADALEAD),0,9),'d/MM/yyyy')
            WHEN TRY_CAST(TRIM(substring(TRIM(FECHALLEGADALEAD),0,9)) AS date) IS NOT NULL
                  THEN to_date(substring(TRIM(FECHALLEGADALEAD),0,10),'d/MM/yyyy') 
            ELSE NULL
        END FECHA_LLEGADA_LEAD,
        TRIM(HORALLEGADALEAD) HORA_LLEGADA_LEAD,
        TRIM(FLUJOAGIL) FLUJO_AGIL,
        TRIM(IDORIGINAL) ID_ORIGINAL,
        UPPER(TRIM(FIRST_NAME)) NOMBRE,
        UPPER(TRIM(LAST_NAME)) APELLIDO,
        TRIM(EMAIL) EMAIL,
        TRIM(EDADPROMEDIO) EDAD_PROMEDIO,
        TRIM(STATE) ESTADO,
        TRIM(CITY) CIUDAD,
        TRIM(STREET) CALLE,
        TRIM(ZIP) CODIGO_POSTAL,
        cast(regexp_extract( replace(replace(TRIM(INGRESOS),'.',''),' ','') , '[0-9]+',0) as numeric(18,2)) INGRESOS,
        TRIM(RIESGO) RIESGO,
        TRIM(ACTIVIDADECONOMICA) ACTIVIDAD_ECONOMICA,
        TRIM(CLASIFICACION) CLASIFICACION,
        TRIM(CAMPANIA) CAMPANIA,
        TRIM(FUENTE) FUENTE,
        TRIM(LINKFUENTE) LINK_FUENTE,
        TRIM(COMPANY) NOMBRE_EMPRESA,
        TRIM(NEGOCIO) NEGOCIO,
        TRIM(ANI1) ANI1,
        TRIM(NUMBER1) PRINCIPAL,
        TRIM(NUMBER2) ALTERNATIVO1,
        TRIM(NUMBER3) ALTERNATIVO2,
        date_format(to_timestamp(trim(substring(CONTACT_CREATE_TIMESTAMP,7,20)),'d MMM yyyy HH:mm:ss'),'yyyy-MM-dd HH:mm:ss') MARCA_HORA_CREACION_CONTACTO,
        date_format(to_timestamp(trim(substring(CONTACT_MODIFIED_TIMESTAMP,7,20)),'d MMM yyyy HH:mm:ss'),'yyyy-MM-dd HH:mm:ss') MARCA_HORA_MODIFICACION_CONTACTO,
        case 
        when length(FECHA_INICIO) = 10 and cast(FECHA_INICIO as date) is not null then cast(FECHA_INICIO as date)
        when length(FECHA_INICIO) < 11 then  to_date(FECHA_INICIO,'d/MM/yyyy')
        else null
        end FECHA_INICIO,
        UPPER(trim(MESLLEGADA)) AS MES_LLEGADA,
        to_date(FECHA_SIG_CUOTA,'d/MM/yyyy') FECHA_SIG_CUOTA,
        cast(regexp_extract( replace(replace(TRIM(VLR_CUOTA),'.',''),' ','') , '[0-9]+',0) as numeric(18,2)) VLR_CUOTA,
        cast(regexp_extract( replace(replace(TRIM(SALDO_CAPITAL),'.',''),' ','') , '[0-9]+',0) as numeric(18,2)) SALDO_CAPITAL,
        INITCAP(TRIM(NUMERODECARGUE)) NUMERO_CARGUE,
        TRIM(OBLIGACION) OBLIGACION,
        TRIM(TIPO_PRODUCTO) TIPO_PRODUCTO,
        cast(regexp_extract( replace(replace(TRIM(CUPOCONSUMO),'.',''),' ','') , '[0-9]+',0) as numeric(18,2)) CUPO_CONSUMO,
        cast(regexp_extract( replace(replace(TRIM(CUPOTDC),'.',''),' ','') , '[0-9]+',0) as numeric(18,2)) CUPO_TDC,
        cast(regexp_extract( replace(replace(TRIM(CUPOTDCCASATORO),'.',''),' ','') , '[0-9]+',0) as numeric(18,2)) CUPO_TDC_CASATORO,
        cast(regexp_extract( replace(replace(TRIM(CUPOTDCBMW),'.',''),' ','') , '[0-9]+',0) as numeric(18,2)) CUPO_TDC_BMW,
        cast(regexp_extract( replace(replace(TRIM(CUPOTDCNACIONAL),'.',''),' ','') , '[0-9]+',0) as numeric(18,2)) CUPO_TDC_NACIONAL,
        cast(regexp_extract( replace(replace(TRIM(CUPOTDCCENTRALMOTOR),'.',''),' ','') , '[0-9]+',0) as numeric(18,2)) CUPO_TDC_CENTRALMOTOR,
        cast(regexp_extract( replace(replace(TRIM(CUPOAUTOEFECTIVO),'.',''),' ','') , '[0-9]+',0) as numeric(18,2)) CUPO_AUTOEFECTIVO,
        cast(regexp_extract( replace(replace(TRIM(CUPORETANQUEO),'.',''),' ','') , '[0-9]+',0) as numeric(18,2)) CUPO_RETANQUEO,
        cast(regexp_extract( replace(replace(TRIM(CUPOMOTORYSA),'.',''),' ','') , '[0-9]+',0) as numeric(18,2)) CUPO_MOTORYSA,
        cast(regexp_extract( replace(replace(TRIM(CUPOBANNERROJO),'.',''),' ','') , '[0-9]+',0) as numeric(18,2)) CUPO_BANNERROJO,
        cast(regexp_extract( replace(replace(TRIM(CUPOPRECALENTAMIENTO),'.',''),' ','') , '[0-9]+',0) as numeric(18,2)) CUPO_PRECALENTAMIENTO,
        cast(regexp_extract( replace(replace(TRIM(BANNERVH),'.',''),' ','') , '[0-9]+',0) as numeric(18,2)) BANNERVH,
        TRIM(TC_A_VENDER) TC_VENDER,
        TRIM(PLAN_APLICA) PLAN_APLICA,
        TRIM(APLICA_REDIFERIDO) APLICA_REDIFERIDO,
        TRIM(TASA) TASA,
        TRIM(TASAACTUAL) TASA_ACTUAL,
        TRIM(PASOACTUAL) PASO_ACTUAL,
        TRIM(PLACA) PLACA,
        TRIM(MODELO) MODELO,
        cast(regexp_extract( replace(replace(TRIM(VALOR_CINCUENTA),'.',''),' ','') , '[0-9]+',0) as numeric(18,2)) VALOR_CINCUENTA,
        cast(regexp_extract( replace(replace(TRIM(VALOR_MORA),'.',''),' ','') , '[0-9]+',0) as numeric(18,2)) VALOR_MORA,
        TRIM(DIAS_MORA) DIAS_MORA,
        TRIM(TEST) TEST,
        TRIM(VIGENCIABASE) VIGENCIA_BASE,
        TRIM(ULTIMA_DISPOSICION) ULTIMA_DISPOSICION,        
        date_format(TIMESTAMP_MILLISECOND, 'yyyy-MM-dd HH:mm:ss.SSS') FECHAHORA,
        TRIM(DATE)  FECHA,
        TRIM(TIME) HORA,
        CAST(TIMESTAMP_ID AS BIGINT) AS TIMESTAMP_ID
  --FROM bronze.five9_contacto
  FROM raw.five9_contacto
  WHERE CAST(TRIM(DATE) AS date) > date_add(current_date(), -7);
);


--Se eliminan de Tabla Silver los registros que existan en la tabla bronze (Campopivot(TIMESTAMP_ID)) para luego ser insertadas:
--DELETE FROM silver.cet_contacto
DELETE FROM master.cet_contacto
WHERE TIMESTAMP_ID IN ( SELECT DISTINCT TIMESTAMP_ID
                        --FROM staging.tmp_five9_contacto
                        FROM tmpstaging_five9_contacto
                      );


--Se insertan los nuevos registros por (Campopivot(TIMESTAMP_ID))
INSERT INTO silver.cet_contacto (
    ID_CONTACTO,
    ID,
    ID_SOLICITUD,
    FECHA_LLEGADA_LEAD,
    HORA_LLEGADA_LEAD,
    FLUJO_AGIL,
    ID_ORIGINAL,
    NOMBRE,
    APELLIDO,
    EMAIL,
    EDAD_PROMEDIO,
    ESTADO,
    CIUDAD,
    CALLE,
    CODIGO_POSTAL,
    INGRESOS,
    RIESGO,
    ACTIVIDAD_ECONOMICA,
    CLASIFICACION,
    CAMPANIA,
    FUENTE,
    LINK_FUENTE,
    NOMBRE_EMPRESA,
    NEGOCIO,
    ANI1,
    PRINCIPAL,
    ALTERNATIVO1,
    ALTERNATIVO2,
    MARCA_HORA_CREACION_CONTACTO,
    MARCA_HORA_MODIFICACION_CONTACTO,
    FECHA_INICIO,
    MES_LLEGADA,
    FECHA_SIG_CUOTA,
    VLR_CUOTA,
    SALDO_CAPITAL,
    NUMERO_CARGUE,
    OBLIGACION,
    TIPO_PRODUCTO, 
    CUPO_CONSUMO,
    CUPO_TDC,
    CUPO_TDC_CASATORO,
    CUPO_TDC_BMW,
    CUPO_TDC_NACIONAL,
    CUPO_TDC_CENTRALMOTOR,
    CUPO_AUTOEFECTIVO,
    CUPO_RETANQUEO,
    CUPO_MOTORYSA,
    CUPO_BANNERROJO,
    CUPO_PRECALENTAMIENTO,
    BANNERVH,
    TC_VENDER, 
    PLAN_APLICA,
    APLICA_REDIFERIDO,
    TASA,
    TASA_ACTUAL,
    PASO_ACTUAL,
    PLACA,
    MODELO,
    VALOR_CINCUENTA,
    VALOR_MORA,
    DIAS_MORA,
    TEST,
    VIGENCIA_BASE,
    ULTIMA_DISPOSICION,
    FECHAHORA,
    FECHA,
    HORA,
    TIMESTAMP_ID
)
  SELECT DISTINCT
        bc.ID_CONTACTO,
        bc.ID,
        bc.ID_SOLICITUD,
        bc.FECHA_LLEGADA_LEAD,
        bc.HORA_LLEGADA_LEAD,
        bc.FLUJO_AGIL,
        bc.ID_ORIGINAL,
        bc.NOMBRE,
        bc.APELLIDO,
        bc.EMAIL,
        bc.EDAD_PROMEDIO,
        bc.ESTADO,
        bc.CIUDAD,
        bc.CALLE,
        bc.CODIGO_POSTAL,
        bc.INGRESOS,
        bc.RIESGO,
        bc.ACTIVIDAD_ECONOMICA,
        bc.CLASIFICACION,
        bc.CAMPANIA,
        bc.FUENTE,
        bc.LINK_FUENTE,
        bc.NOMBRE_EMPRESA,
        bc.NEGOCIO,
        bc.ANI1,
        bc.PRINCIPAL,
        bc.ALTERNATIVO1,
        bc.ALTERNATIVO2,
        bc.MARCA_HORA_CREACION_CONTACTO,
        bc.MARCA_HORA_MODIFICACION_CONTACTO,
        bc.FECHA_INICIO,
        bc.MES_LLEGADA,
        bc.FECHA_SIG_CUOTA,
        bc.VLR_CUOTA,
        bc.SALDO_CAPITAL,
        bc.NUMERO_CARGUE,
        bc.OBLIGACION,
        bc.TIPO_PRODUCTO, 
        bc.CUPO_CONSUMO,
        bc.CUPO_TDC,
        bc.CUPO_TDC_CASATORO,
        bc.CUPO_TDC_BMW,
        bc.CUPO_TDC_NACIONAL,
        bc.CUPO_TDC_CENTRALMOTOR,
        bc.CUPO_AUTOEFECTIVO,
        bc.CUPO_RETANQUEO,
        bc.CUPO_MOTORYSA,
        bc.CUPO_BANNERROJO,
        bc.CUPO_PRECALENTAMIENTO,
        bc.BANNERVH,
        bc.TC_VENDER, 
        bc.PLAN_APLICA,
        bc.APLICA_REDIFERIDO,
        bc.TASA,
        bc.TASA_ACTUAL,
        bc.PASO_ACTUAL,
        bc.PLACA,
        bc.MODELO,
        bc.VALOR_CINCUENTA,
        bc.VALOR_MORA,
        bc.DIAS_MORA,
        bc.TEST,
        bc.VIGENCIA_BASE,
        bc.ULTIMA_DISPOSICION,
        bc.FECHAHORA,
        bc.FECHA,
        bc.HORA,
        bc.TIMESTAMP_ID
  ---FROM staging.tmp_five9_contacto AS bc
  FROM tmpstaging_five9_contacto AS bc
  --LEFT JOIN silver.cet_contacto AS sc
  LEFT JOIN master.cet_contacto AS sc
    ON bc.TIMESTAMP_ID = sc.TIMESTAMP_ID
  WHERE sc.TIMESTAMP_ID IS NULL;


---five9_ivr>>>
--Se crea Tabla Temporal con las trasformaciones aplicadas a la tabla bronze (IVR):
with tmpstaging_five9_ivr as(
--CREATE OR REPLACE TABLE staging.tmp_five9_ivr AS
  SELECT DISTINCT
        TRIM(IVR_SESSION_ID) AS ID_SESION_IVR,
        TRIM(IVR_SCRIPT) AS GUION_IVR,
        CAST(TRIM(VOICE_IVR) AS smallint) AS IVR_VOZ,
        CAST(TRIM(VISUAL_IVR) AS smallint) AS IVR_VISUAL,
        TRIM(MEDIA_TYPE) AS TIPO_MEDIOS,
        TRIM(IVR_TIME) AS TIEMPO_IVR,
        TRIM(IVR_PATH) AS RUTA_IVR,
        TRIM(PATH_TO_AGENT) AS RUTA_AGENTE,
        TRIM(PATH_TO_AGENT_TRANSFER) AS RUTA_TRANSFERENCIA_AGENTE,
        TRIM(PATH_WITH_MAX_AGENT_TRANSFER) AS RUTA_TRANSFERENCIA_MAXIMA_AGENTE,
        TRIM(PATH_TO_ABANDON) AS RUTA_ABANDONO_LLAMADA,
        TRIM(PATH_TO_SKILL) AS RUTA_COMPETENCIA,
        TRIM(PATH_TO_NO_MATCH) AS RUTA_SIN_COINCIDENCIA,
        TRIM(IVR_TIME_TO_FIRST_PROMPT) AS TIEMPO_IVR_PRIMER_MENSAJE,
        TRIM(IVR_TIME_TO_FIRST_QUEUE) AS TIEMPO_IVR_PRIMERA_COLA,
        TRIM(IVR_TIME_TO_ABANDON) AS TIEMPO_IVR_ABANDONO_LLAMADA,
        CAST(TRIM(CALLS_COMPLETED_IN_IVR) AS smallint) AS LLAMADAS_COMPLETADAS_IVR,
        CAST(TRIM(CALLS_DISCONNECTED_IN_IVR) AS smallint) AS LLAMADAS_DESCONECTADAS_IVR,
        CAST(TRIM(CALLS_ABANDONED_IN_QUEUE) AS smallint) AS LLAMADAS_ABANDONADAS_COLA,
        CAST(TRIM(CALLS_TRANSFERRED_TO_AGENT) AS smallint) AS LLAMADAS_TRANSFERIDAS_AGENTE,
        TRIM(CALL_ID) AS ID_LLAMADA,
        DATE_FORMAT(CAST(TRIM(TIMESTAMP_MILLISECOND) AS timestamp), 'yyyy-MM-dd HH:mm:ss.SSS') AS FECHAHORA,
        CAST(TRIM(DATE) AS date) AS FECHA,
        TRIM(TIME) AS HORA,
        CAST(TIMESTAMP_ID AS bigint) AS TIMESTAMP_ID
  --FROM bronze.five9_ivr
  FROM raw.five9_ivr
  WHERE CAST(TRIM(DATE) AS date) > date_add(current_date(), -7);
);


--Se eliminan de Tabla silver los registros que existan en la tabla bronze por (Campopivot(TIMESTAMP_ID)) para luego ser insertadas:
--DELETE FROM silver.cet_respuestainteractiva
DELETE FROM master.cet_respuestainteractiva
WHERE TIMESTAMP_ID IN ( SELECT DISTINCT TIMESTAMP_ID
                        --FROM staging.tmp_five9_ivr
                        FROM tmpstaging_five9_ivr
                      );


--Se insertan los nuevos registros por (Campopivot(TIMESTAMP_ID))
---INSERT INTO silver.cet_respuestainteractiva (
INSERT INTO master.cet_respuestainteractiva (    
    ID_SESION_IVR,
    GUION_IVR,
    IVR_VOZ,
    IVR_VISUAL,
    TIPO_MEDIOS,
    TIEMPO_IVR,
    RUTA_IVR,
    RUTA_AGENTE,
    RUTA_TRANSFERENCIA_AGENTE,
    RUTA_TRANSFERENCIA_MAXIMA_AGENTE,
    RUTA_ABANDONO_LLAMADA,
    RUTA_COMPETENCIA,
    RUTA_SIN_COINCIDENCIA,
    TIEMPO_IVR_PRIMER_MENSAJE,
    TIEMPO_IVR_PRIMERA_COLA,
    TIEMPO_IVR_ABANDONO_LLAMADA,
    LLAMADAS_COMPLETADAS_IVR,
    LLAMADAS_DESCONECTADAS_IVR,
    LLAMADAS_ABANDONADAS_COLA,
    LLAMADAS_TRANSFERIDAS_AGENTE,
    ID_LLAMADA,
    FECHAHORA,
    FECHA,
    HORA,
    TIMESTAMP_ID
)
    SELECT DISTINCT
        bi.ID_SESION_IVR,
        bi.GUION_IVR,
        bi.IVR_VOZ,
        bi.IVR_VISUAL,
        bi.TIPO_MEDIOS,
        bi.TIEMPO_IVR,
        bi.RUTA_IVR,
        bi.RUTA_AGENTE,
        bi.RUTA_TRANSFERENCIA_AGENTE,
        bi.RUTA_TRANSFERENCIA_MAXIMA_AGENTE,
        bi.RUTA_ABANDONO_LLAMADA,
        bi.RUTA_COMPETENCIA,
        bi.RUTA_SIN_COINCIDENCIA,
        bi.TIEMPO_IVR_PRIMER_MENSAJE,
        bi.TIEMPO_IVR_PRIMERA_COLA,
        bi.TIEMPO_IVR_ABANDONO_LLAMADA,
        bi.LLAMADAS_COMPLETADAS_IVR,
        bi.LLAMADAS_DESCONECTADAS_IVR,
        bi.LLAMADAS_ABANDONADAS_COLA,
        bi.LLAMADAS_TRANSFERIDAS_AGENTE,
        bi.ID_LLAMADA,
        bi.FECHAHORA,
        bi.FECHA,
        bi.HORA,
        bi.TIMESTAMP_ID
    ---FROM staging.tmp_five9_ivr AS bi
    FROM tmpstaging_five9_ivr AS bi
    LEFT JOIN master.cet_respuestainteractiva AS si
        ON bi.TIMESTAMP_ID = si.TIMESTAMP_ID
    WHERE si.TIMESTAMP_ID IS NULL;



---MODULOCET: five9_modulo>>>
--Se crea Tabla Temporal con las trasformaciones aplicadas a la tabla bronze (Modulo):
with tmpstaging_five9_modulo as(
--CREATE OR REPLACE TABLE staging.tmp_five9_modulo AS
  SELECT DISTINCT
        TRIM(MODULE) AS MODULO,
        TRIM(MODULE_TYPE) AS TIPO_MODULO,
        TRIM(MODULE_TIME) AS HORA_MODULO,
        TRIM(PATH_TO_MODULE) AS RUTA_AL_MODULO,
        DATE_FORMAT(to_timestamp(trim(substring(MODULE_START_TIMESTAMP,7,20)),'d MMM yyyy HH:mm:ss'),'yyyy-MM-dd HH:mm:ss') AS MARCA_HORA_INICIO_MODULO,
        CAST(TRIM(QUERY_MODULE_LATENCY) AS int) AS LATENCIA_MODULO_CONSULTA,
        CAST(TRIM(QUERY_MODULE_TIMEOUT) AS int) AS AGOTAMIENTO_TIEMPO_ESPERA_MODULO_CONSULTA,
        CAST(TRIM(QUERY_MODULE_ERROR) AS int) AS ERROR_MODULO_CONSULTA,
        CAST(TRIM(TERMINATIONS) AS int) AS TERMINACIONES,
        TRIM(RECORDING) AS GRABACION,
        TRIM(IVR_TIME_TO_MODULE) AS TIEMPO_IVR_MODULO,
        CAST(TRIM(SPEECH_INPUTS) AS int) AS ENTRADAS_VOZ,
        CAST(TRIM(DTMF_INPUTS) AS smallint) AS ENTRADAS_DTMF,
        TRIM(USER_INPUT) AS ENTRADA_USUARIO,
        CAST(TRIM(INPUT_ATTEMPTS) AS int) AS INTENTOS_ENTRADA,
        TRIM(INPUT_TIMEOUTS) AS TIEMPOS_ESPERA_ENTRADA_AGOTADOS,
        TRIM(SILENCE_TIMEOUTS) AS TIEMPOS_ESPERA_SILENCIO_AGOTADOS,
        TRIM(IVR_SESSION_ID) AS ID_SESION_IVR,
        DATE_FORMAT(CAST(TRIM(TIMESTAMP_MILLISECOND) AS timestamp), 'yyyy-MM-dd HH:mm:ss.SSS') AS FECHAHORA,
        CAST(TRIM(DATE) AS date) AS FECHA,
        TRIM(TIME) AS HORA,
        CAST(TIMESTAMP_ID AS bigint) AS TIMESTAMP_ID
  --FROM bronze.five9_modulo
  FROM raw.five9_modulo
  WHERE CAST(TRIM(DATE) AS date) > date_add(current_date(), -7);
);


--Se eliminan de Tabla Silver los registros que existan en la Tabla bronze por (Campopivot(TIMESTAMP_ID)) para luego ser insertadas:
--DELETE FROM silver.cet_modulo
DELETE FROM master.cet_modulo
WHERE TIMESTAMP_ID IN ( SELECT DISTINCT TIMESTAMP_ID
                        FROM tmpstaging_five9_modulo
                      );


--Se insertan los nuevos registros por (Campopivot(TIMESTAMP_ID))
INSERT INTO master.cet_modulo (
    MODULO,
    TIPO_MODULO,
    HORA_MODULO,
    RUTA_AL_MODULO,
    MARCA_HORA_INICIO_MODULO,
    LATENCIA_MODULO_CONSULTA,
    AGOTAMIENTO_TIEMPO_ESPERA_MODULO_CONSULTA,
    ERROR_MODULO_CONSULTA,
    TERMINACIONES,
    GRABACION,
    TIEMPO_IVR_MODULO,
    ENTRADAS_VOZ,
    ENTRADAS_DTMF,
    ENTRADA_USUARIO,
    INTENTOS_ENTRADA,
    TIEMPOS_ESPERA_ENTRADA_AGOTADOS,
    TIEMPOS_ESPERA_SILENCIO_AGOTADOS,
    ID_SESION_IVR,
    FECHAHORA,
    FECHA,
    HORA,
    TIMESTAMP_ID
)
  SELECT DISTINCT
        bm.MODULO,
        bm.TIPO_MODULO,
        bm.HORA_MODULO,
        bm.RUTA_AL_MODULO,
        bm.MARCA_HORA_INICIO_MODULO,
        bm.LATENCIA_MODULO_CONSULTA,
        bm.AGOTAMIENTO_TIEMPO_ESPERA_MODULO_CONSULTA,
        bm.ERROR_MODULO_CONSULTA,
        bm.TERMINACIONES,
        bm.GRABACION,
        bm.TIEMPO_IVR_MODULO,
        bm.ENTRADAS_VOZ,
        bm.ENTRADAS_DTMF,
        bm.ENTRADA_USUARIO,
        bm.INTENTOS_ENTRADA,
        bm.TIEMPOS_ESPERA_ENTRADA_AGOTADOS,
        bm.TIEMPOS_ESPERA_SILENCIO_AGOTADOS,
        bm.ID_SESION_IVR,
        bm.FECHAHORA,
        bm.FECHA,
        bm.HORA,
        bm.TIMESTAMP_ID
  FROM tmpstaging_five9_modulo AS bm
  LEFT JOIN master.cet_modulo AS sm
    ON bm.TIMESTAMP_ID = sm.TIMESTAMP_ID
  WHERE sm.TIMESTAMP_ID IS NULL;



--- CONTACTABILIDADCET: five9_llamadas_estadisticas>>>
--Se crea Tabla Temporal con las trasformaciones aplicadas a la tabla bronze (Llamadas):
with tmpstaging_five9_llamadas_estadisticas as(
--CREATE OR REPLACE TABLE staging.tmp_five9_llamadas_estadisticas AS
  SELECT DISTINCT
        TRIM(CALL_ID) AS ID_LLAMADA,
        TRIM(CALL_TYPE) AS TIPO_LLAMADA,
        TRIM(CAMPAIGN) AS CAMPANA,
        TRIM(CAMPAIGN_TYPE) AS TIPO_CAMPANA,
        TRIM(DISPOSITION) AS DISPOSICION,
        TRIM(DISPOSITION_GROUP_A) AS GRUPOA_DISPOSICIONES,
        TRIM(DISPOSITION_GROUP_B) AS GRUPOB_DISPOSICIONES,
        TRIM(DISPOSITION_GROUP_C) AS GRUPOC_DISPOSICIONES,
        TRIM(DISPOSITION_PATH) AS RUTA_DISPOSICION,
        TRIM(NOTES) AS NOTAS,
        TRIM(SKILL) AS COMPETENCIA,
        TRIM(LIST_NAME) AS NOMBRE_LISTA,
        DATE_FORMAT(CAST(TRIM(TIMESTAMP_MILLISECOND) AS timestamp), 'yyyy-MM-dd HH:mm:ss.SSS') MARCA_HORA_MILISEGUNDOS,
        CAST(TRIM(DATE) AS date) AS FECHA,
        TRIM(TIME) AS HORA,
        TRIM(SESSION_ID) AS ID_SESION,
        TRIM(PARENT_SESSION_ID) AS ID_SESION_MATRIZ,
        TRIM(DNIS) AS DNIS,
        TRIM(DNIS_AREA_CODE) AS CODIGO_AREA_DNIS,
        TRIM(DNIS_STATE) AS ESTADO_DNIS,
        TRIM(DNIS_COUNTRY_CODE) AS CODIGO_PAIS_DNIS,
        TRIM(DNIS_COUNTRY) AS PAIS_DNIS,
        TRIM(ANI) AS ANI,
        TRIM(ANI_COUNTRY_CODE) AS CODIGO_PAIS_ANI,
        TRIM(ANI_COUNTRY) AS PAIS_ANI,
        CAST(TRIM(CALLS) AS int) AS LLAMADAS,
        CAST(TRIM(CONTACTED) AS smallint) AS CONTACTADOS,
        CAST(TRIM(LIVE_CONNECT) AS smallint) AS CONEXION_INTERLOCUTOR_HUMANO,
        CAST(TRIM(NO_PARTY_CONTACT) AS smallint) AS SIN_CONTACTO_INTERLOCUTOR_HUMANO,
        TRIM(SPEED_OF_ANSWER) AS VELOCIDAD_RESPUESTA,
        TRIM(RECORDINGS) AS GRABACIONES,
        CAST(TRIM(SERVICE_LEVEL) AS smallint) AS NIVEL_SERVICIO,
        TRIM(CALL_SURVEY_RESULT) AS RESULTADO_ENCUESTA_LLAMADA,
        CAST(TRIM(ABANDONED) AS smallint) AS ABANDONADA,
        TRIM(ABANDON_RATE) AS INDICE_LLAMADAS_ABANDONADAS,
        TRIM(DISCONNECTED_FROM_HOLD) AS DESCONECTO_ESPERA,
        CAST(TRIM(CALLS_TIMED_OUT_IN_IVR) AS smallint) AS AGOTO_TIEMPO_ESPERA_LLAMADAS_IVR,
        TRIM(TALK_TIME) AS DURACION_LLAMADA,
        TRIM(CALL_TIME) AS TIEMPO_LLAMADA,
        TRIM(DIAL_TIME) AS TIEMPO_MARCACION,
        TRIM(HOLD_TIME) AS TIEMPO_ESPERA,
        TRIM(PARK_TIME) AS TIEMPO_ESPERA_PROLONGADA,
        TRIM(QUEUE_WAIT_TIME) AS TIEMPO_ESPERA_COLA,
        TRIM(TOTAL_QUEUE_TIME) AS TIEMPO_COLA_TOTAL,
        TRIM(QUEUE_CALLBACK_WAIT_TIME) AS TIEMPO_ESPERA_DEVOLUCION_LLAMADAS_COLA,
        TRIM(HANDLE_TIME) AS TIEMPO_ATENCION,
        TRIM(AFTER_CALL_WORK_TIME) AS TIEMPO_TRABAJO_DESPUES_LLAMADA,
        TRIM(IVR_TIME) AS TIEMPO_IVR,
        TRIM(PREVIEW_TIME) AS TIEMPO_PREVISUALIZACION,
        TRIM(RING_TIME) AS TIEMPO_REPIQUE,
        TRIM(BILL_TIME_ROUNDED) AS TIEMPO_FACTURACION_REDONDEO,
        TRIM(MANUAL_TIME) AS TIEMPO_MANUAL,
        CAST(TRIM(CONFERENCES) AS int) AS CONFERENCIAS,
        TRIM(CONFERENCE_TIME) AS HORA_CONFERENCIA,
        TRIM(CONSULT_TIME) AS HORA_CONSULTA,
        CAST(TRIM(TRANSFERS) AS int) AS TRANSFERENCIAS,
        CAST(TRIM(RATE) AS decimal(20,4))AS INDICE,
        CAST(TRIM(HOLDS) AS int) AS ESPERAS,
        CAST(TRIM(PARKS) AS int) AS ESPERAS_PROLONGADAS,
        TRIM(TIME_TO_ABANDON) AS HORA_ABANDONO_LLAMADAS,
        CAST(TRIM(QUEUE_CALLBACK_REGISTERED) AS int) AS DEVOLUCION_LLAMADAS_COLA_REGISTRADAS,
        CAST(TRIM(QUEUE_CALLBACK_PROCESSING) AS int) AS PROCESAMIENTO_DEVOLUCION_LLAMADAS_COLA,
        CAST(TRIM(COST) AS decimal(20,4)) AS COSTO,
        TRIM(VIDEO_TIME) AS DURACION_VIDEO,
        TRIM(3RD_PARTY_TALK_TIME) AS DURACION_LLAMADA_TERCERO,
        TRIM(TALK_TIME_LESS_HOLD_AND_PARK) AS DURACION_LLAMADA_MENOS_TIEMPO_ESPERA_ESPERA_PROLONGADA,
        CAST(TRIM(PREVIEW_INTERRUPTED) AS int) AS VISTA_PREVIA_INTERRUMPIDA,
        CAST(TRIM(PREVIEW_INTERRUPTED_BY_CALL) AS int) AS VISTA_PREVIA_INTERRUMPIDA_LLAMADA,
        CAST(TRIM(PREVIEW_INTERRUPTED_BY_SKILL_VM) AS int) AS VISTA_PREVIA_INTERRUMPIDA_CORREO_VOZ_GRUPO_COMPETENCIAS,
        CAST(TRIM(VOICEMAILS) AS int) AS CORREOS_VOZ,
        CAST(TRIM(VOICEMAILS_HANDLED) AS int) AS CORREOS_VOZ_ATENDIDOS,
        CAST(TRIM(VOICEMAILS_TRANSFERRED) AS int) AS CORREOS_VOZ_TRANSFERIDOS,
        CAST(TRIM(VOICEMAILS_DELETED) AS int) AS CORREOS_VOZ_BORRADOS,
        CAST(TRIM(VOICEMAILS_DECLINED) AS int) AS CORREOS_VOZ_RECHAZADOS,
        CAST(TRIM(VOICEMAILS_RETURNED_CALL) AS int) AS LLAMADA_DEVUELTA_A_CORREOS_VOZ,
        TRIM(VOICEMAILS_HANDLE_TIME) AS TIEMPO_ATENCION_CORREO_VOZ,

        TRIM(survey_Agilidad) AS ENCUESTA_AGILIDAD,
        TRIM(survey_NPS) AS ENCUESTA_NPS,
        TRIM(survey_Amabilidad) AS ENCUESTA_AMABILIDAD,
        TRIM(survey_Informacion) AS ENCUESTA_INFORMACION,
        TRIM(survey_Gusto) AS ENCUESTA_GUSTO,
        COALESCE(TRIM(SAC_Arbol_TDC),TRIM(SAC_Arbol_TDC_)) AS ARBOL_PRODUCTO_TDC,
        COALESCE(TRIM(SAC_Arbol_CDT),TRIM(SAC_Arbol_CDT_)) AS ARBOL_PRODUCTO_CDT,
        COALESCE(TRIM(SAC_Arbol_CUENTAS_DE_AHORRO),TRIM(SAC_Arbol_CUENTAS_DE_AHORRO_)) AS ARBOL_PRODUCTO_CUENTAS_DE_AHORRO,
        COALESCE(TRIM(SAC_Arbol_VEHICULO),TRIM(SAC_Arbol_VEHICULO_)) AS ARBOL_PRODUCTO_VEHICULO,
        COALESCE(TRIM(SAC_Arbol_LIBRANZA),TRIM(SAC_Arbol_LIBRANZAS_)) AS ARBOL_PRODUCTO_LIBRANZA,
        COALESCE(TRIM(SAC_Arbol_CONSUMO),TRIM(SAC_Arbol_CONSUMO_)) AS ARBOL_PRODUCTO_CONSUMO,
        TRIM(Arbol_Seguros_SEGUROS) AS ARBOL_PRODUCTO_SEGUROS,
        COALESCE(TRIM(SAC_Arbol_INFORMACION_GENERAL_Y_PORTALES),TRIM(SAC_Arbol_INFORMACION_GENERAL_Y_PORTALES_)) AS ARBOL_INFORMACION_GENERAL,
        TRIM(Arbol_COB_ARBOL_COBRANZAS_) AS ARBOL_COBRANZAS,
        TRIM(Arbol_InBound_Ventas_VENTAS_) AS ARBOL_VENTAS,

        TRIM(AGENT_ID) AS ID_AGENTE,
        TRIM(CONTACT_ID) AS ID_CONTACTO,
        CAST(TIMESTAMP_ID AS bigint) AS TIMESTAMP_ID
  FROM raw.five9_llamadas_estadisticas
  WHERE CAST(TRIM(DATE) AS date) > date_add(current_date(), -7)
);


df = sqlContext.sql("""
                    SELECT
                      ID_LLAMADA,
                      NOTAS
                    ---FROM staging.tmp_five9_llamadas_estadisticas
                    FROM tmpstaging_five9_llamadas_estadisticas
                    WHERE NOTAS IS NOT null
                    """)
df =  df.withColumn("text", limpiarF(col("NOTAS")))
df.createOrReplaceTempView("texto")


--Se eliminan de Tabla Silver los registros que existan en la Tabla bronze por (Campopivot(TIMESTAMP_ID)) para luego ser insertadas:
DELETE FROM master.cet_contactabilidad
WHERE TIMESTAMP_ID IN ( SELECT DISTINCT TIMESTAMP_ID
                        --FROM staging.tmp_five9_llamadas_estadisticas
                        FROM tmpstaging_five9_llamadas_estadisticas
                      );


--Se insertan los nuevos registros por (Campopivot(TIMESTAMP_ID))
INSERT INTO master.cet_contactabilidad (
    ID_LLAMADA,
    TIPO_LLAMADA,
    CAMPANA,
    TIPO_CAMPANA,
    DISPOSICION,
    GRUPOA_DISPOSICIONES,
    GRUPOB_DISPOSICIONES,
    GRUPOC_DISPOSICIONES,
    RUTA_DISPOSICION,
    NOTAS,
    COMPETENCIA,
    NOMBRE_LISTA,
    MARCA_HORA_MILISEGUNDOS,
    FECHA,
    HORA,
    ID_SESION,
    ID_SESION_MATRIZ,
    DNIS,
    CODIGO_AREA_DNIS,
    ESTADO_DNIS,
    CODIGO_PAIS_DNIS,
    PAIS_DNIS,
    ANI,
    CODIGO_PAIS_ANI,
    PAIS_ANI,
    LLAMADAS,
    CONTACTADOS,
    CONEXION_INTERLOCUTOR_HUMANO,
    SIN_CONTACTO_INTERLOCUTOR_HUMANO,
    VELOCIDAD_RESPUESTA,
    GRABACIONES,
    NIVEL_SERVICIO,
    RESULTADO_ENCUESTA_LLAMADA,
    ABANDONADA,
    INDICE_LLAMADAS_ABANDONADAS,
    DESCONECTO_ESPERA,
    AGOTO_TIEMPO_ESPERA_LLAMADAS_IVR,
    DURACION_LLAMADA,
    TIEMPO_LLAMADA,
    TIEMPO_MARCACION,
    TIEMPO_ESPERA,
    TIEMPO_ESPERA_PROLONGADA,
    TIEMPO_ESPERA_COLA,
    TIEMPO_COLA_TOTAL,
    TIEMPO_ESPERA_DEVOLUCION_LLAMADAS_COLA,
    TIEMPO_ATENCION,
    TIEMPO_TRABAJO_DESPUES_LLAMADA,
    TIEMPO_IVR,
    TIEMPO_PREVISUALIZACION,
    TIEMPO_REPIQUE,
    TIEMPO_FACTURACION_REDONDEO,
    TIEMPO_MANUAL,
    CONFERENCIAS,
    HORA_CONFERENCIA,
    HORA_CONSULTA,
    TRANSFERENCIAS,
    INDICE,
    ESPERAS,
    ESPERAS_PROLONGADAS,
    HORA_ABANDONO_LLAMADAS,
    DEVOLUCION_LLAMADAS_COLA_REGISTRADAS,
    PROCESAMIENTO_DEVOLUCION_LLAMADAS_COLA,
    COSTO,
    DURACION_VIDEO,
    DURACION_LLAMADA_TERCERO,
    DURACION_LLAMADA_MENOS_TIEMPO_ESPERA_ESPERA_PROLONGADA,
    VISTA_PREVIA_INTERRUMPIDA,
    VISTA_PREVIA_INTERRUMPIDA_LLAMADA,
    VISTA_PREVIA_INTERRUMPIDA_CORREO_VOZ_GRUPO_COMPETENCIAS,
    CORREOS_VOZ,
    CORREOS_VOZ_ATENDIDOS,
    CORREOS_VOZ_TRANSFERIDOS,
    CORREOS_VOZ_BORRADOS,
    CORREOS_VOZ_RECHAZADOS,
    LLAMADA_DEVUELTA_A_CORREOS_VOZ,
    TIEMPO_ATENCION_CORREO_VOZ,

    ENCUESTA_AGILIDAD,
    ENCUESTA_NPS,
    ENCUESTA_AMABILIDAD,
    ENCUESTA_INFORMACION,
    ENCUESTA_GUSTO,
    ARBOL_PRODUCTO_TDC,
    ARBOL_PRODUCTO_CDT,
    ARBOL_PRODUCTO_CUENTAS_DE_AHORRO,
    ARBOL_PRODUCTO_VEHICULO,
    ARBOL_PRODUCTO_LIBRANZA,
    ARBOL_PRODUCTO_CONSUMO,
    ARBOL_PRODUCTO_SEGUROS,
    ARBOL_INFORMACION_GENERAL,
    ARBOL_COBRANZAS,
    ARBOL_VENTAS,

    ID_AGENTE,
    ID_CONTACTO,
    TIMESTAMP_ID
)
  SELECT DISTINCT
        bl.ID_LLAMADA,
        bl.TIPO_LLAMADA,
        bl.CAMPANA,
        bl.TIPO_CAMPANA,
        bl.DISPOSICION,
        bl.GRUPOA_DISPOSICIONES,
        bl.GRUPOB_DISPOSICIONES,
        bl.GRUPOC_DISPOSICIONES,
        bl.RUTA_DISPOSICION,
        texto.text,
        bl.COMPETENCIA,
        bl.NOMBRE_LISTA,
        bl.MARCA_HORA_MILISEGUNDOS,
        bl.FECHA,
        bl.HORA,
        bl.ID_SESION,
        bl.ID_SESION_MATRIZ,
        bl.DNIS,
        bl.CODIGO_AREA_DNIS,
        bl.ESTADO_DNIS,
        bl.CODIGO_PAIS_DNIS,
        bl.PAIS_DNIS,
        bl.ANI,
        bl.CODIGO_PAIS_ANI,
        bl.PAIS_ANI,
        bl.LLAMADAS,
        bl.CONTACTADOS,
        bl.CONEXION_INTERLOCUTOR_HUMANO,
        bl.SIN_CONTACTO_INTERLOCUTOR_HUMANO,
        bl.VELOCIDAD_RESPUESTA,
        bl.GRABACIONES,
        bl.NIVEL_SERVICIO,
        bl.RESULTADO_ENCUESTA_LLAMADA,
        bl.ABANDONADA,
        bl.INDICE_LLAMADAS_ABANDONADAS,
        bl.DESCONECTO_ESPERA,
        bl.AGOTO_TIEMPO_ESPERA_LLAMADAS_IVR,
        bl.DURACION_LLAMADA,
        bl.TIEMPO_LLAMADA,
        bl.TIEMPO_MARCACION,
        bl.TIEMPO_ESPERA,
        bl.TIEMPO_ESPERA_PROLONGADA,
        bl.TIEMPO_ESPERA_COLA,
        bl.TIEMPO_COLA_TOTAL,
        bl.TIEMPO_ESPERA_DEVOLUCION_LLAMADAS_COLA,
        bl.TIEMPO_ATENCION,
        bl.TIEMPO_TRABAJO_DESPUES_LLAMADA,
        bl.TIEMPO_IVR,
        bl.TIEMPO_PREVISUALIZACION,
        bl.TIEMPO_REPIQUE,
        bl.TIEMPO_FACTURACION_REDONDEO,
        bl.TIEMPO_MANUAL,
        bl.CONFERENCIAS,
        bl.HORA_CONFERENCIA,
        bl.HORA_CONSULTA,
        bl.TRANSFERENCIAS,
        bl.INDICE,
        bl.ESPERAS,
        bl.ESPERAS_PROLONGADAS,
        bl.HORA_ABANDONO_LLAMADAS,
        bl.DEVOLUCION_LLAMADAS_COLA_REGISTRADAS,
        bl.PROCESAMIENTO_DEVOLUCION_LLAMADAS_COLA,
        bl.COSTO,
        bl.DURACION_VIDEO,
        bl.DURACION_LLAMADA_TERCERO,
        bl.DURACION_LLAMADA_MENOS_TIEMPO_ESPERA_ESPERA_PROLONGADA,
        bl.VISTA_PREVIA_INTERRUMPIDA,
        bl.VISTA_PREVIA_INTERRUMPIDA_LLAMADA,
        bl.VISTA_PREVIA_INTERRUMPIDA_CORREO_VOZ_GRUPO_COMPETENCIAS,
        bl.CORREOS_VOZ,
        bl.CORREOS_VOZ_ATENDIDOS,
        bl.CORREOS_VOZ_TRANSFERIDOS,
        bl.CORREOS_VOZ_BORRADOS,
        bl.CORREOS_VOZ_RECHAZADOS,
        bl.LLAMADA_DEVUELTA_A_CORREOS_VOZ,
        bl.TIEMPO_ATENCION_CORREO_VOZ,

        bl.ENCUESTA_AGILIDAD,
        bl.ENCUESTA_NPS,
        bl.ENCUESTA_AMABILIDAD,
        bl.ENCUESTA_INFORMACION,
        bl.ENCUESTA_GUSTO,
        bl.ARBOL_PRODUCTO_TDC,
        bl.ARBOL_PRODUCTO_CDT,
        bl.ARBOL_PRODUCTO_CUENTAS_DE_AHORRO,
        bl.ARBOL_PRODUCTO_VEHICULO,
        bl.ARBOL_PRODUCTO_LIBRANZA,
        bl.ARBOL_PRODUCTO_CONSUMO,
        bl.ARBOL_PRODUCTO_SEGUROS,
        bl.ARBOL_INFORMACION_GENERAL,
        bl.ARBOL_COBRANZAS,
        bl.ARBOL_VENTAS,

        bl.ID_AGENTE,
        bl.ID_CONTACTO,
        bl.TIMESTAMP_ID
  FROM tmpstaging_five9_llamadas_estadisticas AS bl
  LEFT JOIN master.cet_contactabilidad AS sl
    ON bl.TIMESTAMP_ID = sl.TIMESTAMP_ID
  LEFT JOIN texto ON TEXTO.ID_LLAMADA = bl.ID_LLAMADA
  WHERE sl.TIMESTAMP_ID IS NULL;



--- REGISTROLISTACET: five9_lista>>>
--Se crea Tabla Temporal con las trasformaciones aplicadas a la tabla bronze (Agente):
with tmpstaging_five9_lista as(
--CREATE OR REPLACE TABLE staging.tmp_five9_lista AS
  SELECT DISTINCT
        TRIM(LIST_RECORD_ID) AS ID_REGISTRO_LISTA,
        TRIM(LIST_NAME) AS NOMBRE_LISTA,
        TRIM(CAMPAIGN) AS CAMPANA,
        TRIM(CAMPAIGN_TYPE) AS TIPO_CAMPANA,
        CAST(TRIM(LIST_RECORDS) AS smallint) AS REGISTROS_LISTAS,
        CAST(TRIM(DIALED_RECORDS) AS smallint) AS REGISTROS_MARCADOS,
        CAST(TRIM(CONTACTED) AS smallint) AS CONTACTADOS,
        TRIM(TIME_TO_FIRST_CONTACT) AS HORA_PRIMER_CONTACTO,
        CAST(TRIM(ATTEMPTS_TO_FIRST_CONTACT) AS int) AS INTENTOS_PRIMER_CONTACTO,
        DATE_FORMAT(to_timestamp(TRIM(substring(FIRST_CONTACT_TIMESTAMP,7,20)),'d MMM yyyy HH:mm:ss'),'yyyy-MM-dd HH:mm:ss') AS MARCA_HORA_PRIMER_CONTACTO,
        CAST(TRIM(DIAL_ATTEMPTS) AS int) AS INTENTOS_MARCACION,
        TRIM(LAST_DISPOSITION) AS ULTIMA_DISPOSICION,
        TRIM(FINAL_DISPOSITION) AS DISPOSICION_FINAL,
        DATE_FORMAT(to_timestamp(TRIM(substring(FINAL_DISPOSITION_TIMESTAMP,7,20)),'d MMM yyyy HH:mm:ss'),'yyyy-MM-dd HH:mm:ss') AS MARCA_HORA_DISPOSICION_FINAL,
        TRIM(LAST_ATTEMPT_CALL_ID) AS ID_LLAMADA_ULTIMO_INTENTO,
        TRIM(LAST_ATTEMPT_PHONE_NUMBER) AS ULTIMO_NUMERO_TELEFONO_INTENTO_LLAMAR,
        DATE_FORMAT(to_timestamp(TRIM(substring(LAST_CALL_TIMESTAMP,7,20)),'d MMM yyyy HH:mm:ss'),'yyyy-MM-dd HH:mm:ss') AS MARCA_HORA_ULTIMA_LLAMADA,
        to_date(LAST_CALL_DAY,'yyyy/MM/dd') AS DIA_ULTIMA_LLAMADA,
        DATE_FORMAT(LAST_CALL_TIME,'HH:mm:ss') HORA_ULTIMA_LLAMADA,
        DATE_FORMAT(to_timestamp(trim(substring(LAST_SKIPPED_TIMESTAMP,7,20)),'d MMM yyyy HH:mm:ss'),'yyyy-MM-dd HH:mm:ss') AS MARCA_HORA_ULTIMO_NUMERO_SALTADO,
        TRIM(LAST_SKIPPED_REASON) AS MOTIVO_ULTIMO_NUMERO_SALTADO,
        TRIM(STATUS) AS ESTADO,
        CAST(TRIM(PROFILE_DISABLED_NUMBER) AS smallint) AS NUMERO_DESHABILITADO_PERFIL,
        CAST(TRIM(UNREACHABLE) AS smallint) AS NO_CONTACTABLES,
        CAST(TRIM(UNREACHABLE_DO_NOT_DIAL) AS smallint) AS NO_CONTACTABLE_NO_MARCAR,
        CAST(TRIM(UNREACHABLE_DNC) AS smallint) AS NO_CONTACTABLE_DNC,
        CAST(TRIM(UNREACHABLE_MAX_ATTEMPTS) AS smallint) AS NO_CONTACTABLE_MAXIMO_INTENTOS,
        CAST(TRIM(FINAL) AS smallint) AS FINAL,
        CAST(TRIM(NEW) AS smallint) AS NUEVO,
        CAST(TRIM(IN_PROGRESS) AS smallint) AS EN_CURSO,
        CAST(TRIM(ASAP_FLAG) AS smallint) AS BANDERA_ASAP,
        DATE_FORMAT(to_timestamp(trim(substring(CONSIDERATION_TIME,7,20)),'d MMM yyyy HH:mm:ss'),'yyyy-MM-dd HH:mm:ss') AS TIEMPO_CONSIDERACION,
        to_date(CONSIDERATION_TIME_DATE,'yyyy/MM/dd') AS TIEMPO_CONSIDERACION_FECHA,
        DATE_FORMAT(to_timestamp(trim(substring(CONSIDERATION_TIME_DATE_AND_HOUR,7,20)),'d MMM yyyy HH:mm'),'yyyy-MM-dd HH:mm') AS TIEMPO_CONSIDERACION_FECHA_HORA,
        TRIM(CONTACT_ID) AS ID_CONTACTO,
        DATE_FORMAT(CAST(TRIM(TIMESTAMP_MILLISECOND) AS timestamp), 'yyyy-MM-dd HH:mm:ss.SSS') AS FECHAHORA,
        CAST(TRIM(DATE) AS date) AS FECHA,
        TRIM(TIME) AS HORA,
        CAST(TIMESTAMP_ID AS bigint) AS TIMESTAMP_ID
  FROM raw.five9_lista
  WHERE CAST(TRIM(DATE) AS date) > date_add(current_date(), -7)
);


--Se eliminan de Tabla Silver los registros que existan en la Tabla bronze por (Campopivot(TIMESTAMP_ID)) para luego ser insertadas:
DELETE FROM master.cet_registrolista
WHERE TIMESTAMP_ID IN ( SELECT DISTINCT TIMESTAMP_ID
                        FROM tmpstaging_five9_lista
                      );


--Se insertan los nuevos registros por (Campopivot(TIMESTAMP_ID))
INSERT INTO master.cet_registrolista (
    ID_REGISTRO_LISTA,
    NOMBRE_LISTA,
    CAMPANA,
    TIPO_CAMPANA,
    REGISTROS_LISTAS,
    REGISTROS_MARCADOS,
    CONTACTADOS,
    HORA_PRIMER_CONTACTO,
    INTENTOS_PRIMER_CONTACTO,
    MARCA_HORA_PRIMER_CONTACTO,
    INTENTOS_MARCACION,
    ULTIMA_DISPOSICION,
    DISPOSICION_FINAL,
    MARCA_HORA_DISPOSICION_FINAL,
    ID_LLAMADA_ULTIMO_INTENTO,
    ULTIMO_NUMERO_TELEFONO_INTENTO_LLAMAR,
    MARCA_HORA_ULTIMA_LLAMADA,
    DIA_ULTIMA_LLAMADA,
    HORA_ULTIMA_LLAMADA,
    MARCA_HORA_ULTIMO_NUMERO_SALTADO,
    MOTIVO_ULTIMO_NUMERO_SALTADO,
    ESTADO,
    NUMERO_DESHABILITADO_PERFIL,
    NO_CONTACTABLES,
    NO_CONTACTABLE_NO_MARCAR,
    NO_CONTACTABLE_DNC,
    NO_CONTACTABLE_MAXIMO_INTENTOS,
    FINAL,
    NUEVO,
    EN_CURSO,
    BANDERA_ASAP,
    TIEMPO_CONSIDERACION,
    TIEMPO_CONSIDERACION_FECHA,
    TIEMPO_CONSIDERACION_FECHA_HORA,
    ID_CONTACTO,
    FECHAHORA,
    FECHA,
    HORA,
    TIMESTAMP_ID
)
  SELECT DISTINCT
        bl.ID_REGISTRO_LISTA,
        bl.NOMBRE_LISTA,
        bl.CAMPANA,
        bl.TIPO_CAMPANA,
        bl.REGISTROS_LISTAS,
        bl.REGISTROS_MARCADOS,
        bl.CONTACTADOS,
        bl.HORA_PRIMER_CONTACTO,
        bl.INTENTOS_PRIMER_CONTACTO,
        bl.MARCA_HORA_PRIMER_CONTACTO,
        bl.INTENTOS_MARCACION,
        bl.ULTIMA_DISPOSICION,
        bl.DISPOSICION_FINAL,
        bl.MARCA_HORA_DISPOSICION_FINAL,
        bl.ID_LLAMADA_ULTIMO_INTENTO,
        bl.ULTIMO_NUMERO_TELEFONO_INTENTO_LLAMAR,
        bl.MARCA_HORA_ULTIMA_LLAMADA,
        bl.DIA_ULTIMA_LLAMADA,
        bl.HORA_ULTIMA_LLAMADA,
        bl.MARCA_HORA_ULTIMO_NUMERO_SALTADO,
        bl.MOTIVO_ULTIMO_NUMERO_SALTADO,
        bl.ESTADO,
        bl.NUMERO_DESHABILITADO_PERFIL,
        bl.NO_CONTACTABLES,
        bl.NO_CONTACTABLE_NO_MARCAR,
        bl.NO_CONTACTABLE_DNC,
        bl.NO_CONTACTABLE_MAXIMO_INTENTOS,
        bl.FINAL,
        bl.NUEVO,
        bl.EN_CURSO,
        bl.BANDERA_ASAP,
        bl.TIEMPO_CONSIDERACION,
        bl.TIEMPO_CONSIDERACION_FECHA,
        bl.TIEMPO_CONSIDERACION_FECHA_HORA,
        bl.ID_CONTACTO,
        bl.FECHAHORA,
        bl.FECHA,
        bl.HORA,
        bl.TIMESTAMP_ID
  FROM tmpstaging_five9_lista AS bl
  LEFT JOIN master.cet_registrolista AS sl
    ON bl.TIMESTAMP_ID = sl.TIMESTAMP_ID
  WHERE sl.TIMESTAMP_ID IS NULL;



--- REPORTETRAFICOCET: five9_trafico>>>
--Se crea Tabla Temporal con las trasformaciones aplicadas a la tabla bronze (Agente):
with tmpstaging_five9_trafico as(
--CREATE OR REPLACE TABLE staging.tmp_five9_trafico AS
  SELECT DISTINCT
         TRIM(SKILL) AS SKILL,
         CAST(TRIM(DATE) AS date) AS FECHA,
         CAST(TRIM(CALLS) AS smallint) AS CANTIDAD_LLAMADAS,
         DATE_FORMAT(SPEED_OF_ANSWER,'HH:mm:ss') VELOCIDAD_RESPUESTA,
         CAST(TRIM(SERVICE_LEVEL) AS smallint) AS NIVEL_SERVICIO,
         CAST(TRIM(ABANDONED) AS smallint) AS ABANDONADO,
         CAST(TRIM(TRANSFERS) AS smallint) AS TRANSFERIDO,
         DATE_FORMAT(HANDLE_TIME,'HH:mm:ss') TIEMPO_MANEJO,
         TRIM(CALL_TYPE) AS TIPO_LLAMADA,
         CAST(TRIM(QUEUE_CALLBACK_REGISTERED) AS smallint) AS COLA_DEVOLUCION_LLAMADAS_REGISTRADAS,
         CAST(TRIM(QUEUE_CALLBACK_PROCESSING) AS smallint) AS COLA_DEVOLUCION_LLAMADAS_PROCESADAS,
         DATE_FORMAT(AFTER_CALL_WORK_TIME,'HH:mm:ss') TIEMPO_DESPUES_LLAMADA,
         CAST(TRIM(HOLDS) AS smallint) AS ESPERA,
         DATE_FORMAT(HOLD_TIME,'HH:mm:ss') TIEMPO_ESPERA,
         DATE_FORMAT(IVR_TIME,'HH:mm:ss') TIEMPO_IVR,
         TRIM(AGENT) AS AGENTE,
         TRIM(CALL_ID) AS ID_LLAMADA,
         TRIM(MONTH) AS MES,
         DATE_FORMAT(HALF_HOUR,'HH:mm:ss') MEDIA_HORA,
         DATE_FORMAT(HOUR,'HH:mm:ss') HORA,
         TRIM(HOUR_OF_DAY) AS HORA_DEL_DIA,
         TRIM(TIME_INTERVAL) AS TIEMPO_INTERVALO,
         DATE_FORMAT(TALK_TIME,'HH:mm:ss') TIEMPO_LLAMADA,
         TRIM(CAMPAIGN) AS CAMPANIA,
         DATE_FORMAT(CAST(TRIM(TIMESTAMP_MILLISECOND) AS timestamp), 'yyyy-MM-dd HH:mm:ss.SSS') AS FECHAHORA,
         CAST(TIMESTAMP_ID AS bigint) AS TIMESTAMP_ID
  FROM raw.five9_trafico
  WHERE CAST(TRIM(DATE) AS date) > date_add(current_date(), -7)
);


--Se eliminan de Tabla Silver los registros que existan en la Tabla bronze por (Campopivot(TIMESTAMP_ID)) para luego ser insertadas:
DELETE FROM master.cet_trafico
WHERE TIMESTAMP_ID IN ( SELECT DISTINCT TIMESTAMP_ID
                        FROM tmpstaging_five9_trafico
                      );


--Se insertan los nuevos registros por (Campopivot(TIMESTAMP_ID))
INSERT INTO master.cet_trafico (
    SKILL,
    FECHA,
    CANTIDAD_LLAMADAS,
    VELOCIDAD_RESPUESTA,
    NIVEL_SERVICIO,
    ABANDONADO,
    TRANSFERIDO,
    TIEMPO_MANEJO,
    TIPO_LLAMADA,
    COLA_DEVOLUCION_LLAMADAS_REGISTRADAS,
    COLA_DEVOLUCION_LLAMADAS_PROCESADAS,
    TIEMPO_DESPUES_LLAMADA,
    ESPERA,
    TIEMPO_ESPERA,
    TIEMPO_IVR,
    AGENTE,
    ID_LLAMADA,
    MES,
    MEDIA_HORA,
    HORA,
    HORA_DEL_DIA,
    TIEMPO_INTERVALO,
    TIEMPO_LLAMADA,
    CAMPANIA,
    FECHAHORA,
    TIMESTAMP_ID
)
  SELECT DISTINCT
        bl.SKILL,
        bl.FECHA,
        bl.CANTIDAD_LLAMADAS,
        bl.VELOCIDAD_RESPUESTA,
        bl.NIVEL_SERVICIO,
        bl.ABANDONADO,
        bl.TRANSFERIDO,
        bl.TIEMPO_MANEJO,
        bl.TIPO_LLAMADA,
        bl.COLA_DEVOLUCION_LLAMADAS_REGISTRADAS,
        bl.COLA_DEVOLUCION_LLAMADAS_PROCESADAS,
        bl.TIEMPO_DESPUES_LLAMADA,
        bl.ESPERA,
        bl.TIEMPO_ESPERA,
        bl.TIEMPO_IVR,
        bl.AGENTE,
        bl.ID_LLAMADA,
        bl.MES,
        bl.MEDIA_HORA,
        bl.HORA,
        bl.HORA_DEL_DIA,
        bl.TIEMPO_INTERVALO,
        bl.TIEMPO_LLAMADA,
        bl.CAMPANIA,
        bl.FECHAHORA,
        CAST(bl.TIMESTAMP_ID AS bigint) AS TIMESTAMP_ID
  FROM tmpstaging_five9_trafico AS bl
  LEFT JOIN master.cet_trafico AS sl
    ON bl.TIMESTAMP_ID = sl.TIMESTAMP_ID
  WHERE sl.TIMESTAMP_ID IS NULL;

DROP TABLE IF EXISTS tmpstaging_five9_agente;
DROP TABLE IF EXISTS tmpstaging_five9_contacto;
DROP TABLE IF EXISTS tmpstaging_five9_ivr;
DROP TABLE IF EXISTS tmpstaging_five9_modulo;
DROP TABLE IF EXISTS tmpstaging_five9_llamadas_estadisticas;
DROP TABLE IF EXISTS tmpstaging_five9_lista;
DROP TABLE IF EXISTS tmpstaging_five9_trafico;


